---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aclerici38/pocket-id-operator/refs/heads/main/dist/chart/values.schema.json
instance:
  spec:
    encryptionKey:
      value: "test-key-16chars"

users:
  - name: test-user
