resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:06eca26c8ec787420fb78d4b314b4235d61809b353f2195060751078edf83352
  name: ghcr.io/aclerici38/pocket-id-operator
  newName: ghcr.io/aclerici38/pocket-id-operator
  newTag: v0.1.1