# This rule is not used by the project pocket-id-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over pocketid.internal.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pocket-id-operator
    app.kubernetes.io/managed-by: kustomize
  name: pocket-id-operator-instance-admin-role
rules:
- apiGroups:
  - pocketid.internal
  resources:
  - instances
  verbs:
  - '*'
- apiGroups:
  - pocketid.internal
  resources:
  - instances/status
  verbs:
  - get
