apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: pocket-id-operator
    app.kubernetes.io/managed-by: kustomize
  name: pocket-id-operator-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pocket-id-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: pocket-id-operator
  namespace: pocket-id-operator-system
