apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: pocket-id-operator
    app.kubernetes.io/managed-by: kustomize
  name: pocket-id-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pocket-id-operator-manager-role
subjects:
- kind: ServiceAccount
  name: pocket-id-operator
  namespace: pocket-id-operator-system
